### ISSUE TITLE
ROS2 Humble run failure

### ISSUE THREAD

**Issue by zweistein** [tosiyuki/rosbag_gui_player#1]
Hi, I tried to run your code in  `ros2 humble` but got an error. Do you know what could be the problem?

```
Traceback (most recent call last):
  File "/home/elod/ros/data_recording/install/data_recording_utils/lib/data_recording_utils/rosbag_gui", line 33, in <module>
    sys.exit(load_entry_point('data-recording-utils==0.0.0', 'console_scripts', 'rosbag_gui')())
  File "/home/elod/ros/data_recording/install/data_recording_utils/lib/data_recording_utils/rosbag_gui", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/elod/ros/data_recording/install/data_recording_utils/lib/python3.10/site-packages/data_recording_utils/ros2bag_gui.py", line 9, in <module>
    import rosbag
  File "/usr/lib/python3/dist-packages/rosbag/__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "/usr/lib/python3/dist-packages/rosbag/bag.py", line 69, in <module>
    import rospy
  File "/usr/lib/python3/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/usr/lib/python3/dist-packages/rospy/client.py", line 54, in <module>
    import rospy.core
  File "/usr/lib/python3/dist-packages/rospy/core.py", line 75, in <module>
    from rosgraph_msgs.msg import Log
ImportError: cannot import name 'Log' from 'rosgraph_msgs.msg' (/opt/ros/humble/local/lib/python3.10/dist-packages/rosgraph_msgs/msg/__init__.py)
[ros2run]: Process exited with failure 1
```

**Comment by zweistein** [comment]
The answer will be simple: this is a ROS(1) bag file GUI. It confused me since rqt_bag provides similar and even better capabilities as far as I know.
